### ISSUE TITLE
Update README.md with installation / getting started instructions.

### ISSUE THREAD

**Issue by jchapin** [nathanhood/nashploration#1]
Look at other github projects for how they cover the installation and getting started documentation for their project.

Getting Nashploration setup is pretty easy:
- cloning the repository
- npm install
- install mongodb
- starting mongos
- node app.js

As discussed yesterday, it would be nice to cover some of the "optional" steps like loading data into Mongo so that you can actually see a set of pins on your map to start with.

Having a set of instructions on how to replace that set of data may also be helpful.

**Comment by nathanhood** [comment]
Thanks John. We will get on this. We are spending a good amount of this weekend on Nashploration. I’m excited to show our progress the next time we see each other. We will make sure to implement the set up instructions you laid out in our README. Thanks again. 

Nathan
