### ISSUE TITLE
wiki data load

### ISSUE THREAD

**Issue by RanSolo** [nathanhood/nashploration#3]
When I enter the command below for loading wiki data

![screenshot 2014-09-13 20 48 19](https://cloud.githubusercontent.com/assets/6284142/4262667/5c2f1186-3bb1-11e4-9938-2cdcb8411f40.png)

I get the eror below

connected to: 127.0.0.1
file doesn't exist: db/wiki.json

![screenshot 2014-09-13 20 46 39](https://cloud.githubusercontent.com/assets/6284142/4262666/5c1cc71a-3bb1-11e4-8770-4edde246e3b8.png)

**Comment by richmondwatkins** [comment]
use db/w.json for the file path ... we are going to change the file name to wiki but haven't done it yet.

**Comment by richmondwatkins** [comment]
@RanSolo still working on this. Hoping to have it fixed by 2017. Only running about 2 years behind.

**Comment by RanSolo** [comment]
@richmondwatkins yeah, I've got a great idea... we should do this but with pokemons.
